package com.banka.corebank.user.service.impl;

import com.banka.corebank.customer.dto.request.CreateCustomerRequest;
import com.banka.corebank.customer.dto.response.CustomerResponse;
import com.banka.corebank.customer.entity.Customer;
import com.banka.corebank.customer.repository.CustomerRepository;
import com.banka.corebank.customer.service.CustomerService;
import com.banka.corebank.exception.ResourceNotFoundException;
import com.banka.corebank.user.dto.request.LoginRequest;
import com.banka.corebank.user.dto.request.RegisterRequest;
import com.banka.corebank.user.dto.response.AuthResponse;
import com.banka.corebank.user.entity.User;
import com.banka.corebank.user.mapper.UserMapper;
import com.banka.corebank.user.repository.UserRepository;
import com.banka.corebank.user.service.UserService;

import java.util.UUID;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserServiceImpl implements UserService {

        private final UserRepository userRepository;
        private final CustomerRepository customerRepository;
        private final CustomerService customerService;
        private final UserMapper userMapper;

        public UserServiceImpl(UserRepository userRepository,
                        CustomerRepository customerRepository,
                        CustomerService customerService,
                        UserMapper userMapper) {
                this.userRepository = userRepository;
                this.customerRepository = customerRepository;
                this.customerService = customerService;
                this.userMapper = userMapper;
        }

        @Override
        public AuthResponse login(LoginRequest request) {
                // Keycloak handles login. This method could be removed or refactored
                // to handle local sync if needed.
                throw new UnsupportedOperationException("Login is now handled by Keycloak");
        }

        @Override
        @Transactional
        public AuthResponse register(RegisterRequest request) {
                // 1. Map DTO to User entity
                User user = userMapper.toEntity(request);

                // 2. No more manual password encryption
                user.setPassword("{noop}keycloak-managed"); // Placeholder

                // 3. Create Customer (Business Data)
                String fullName = request.firstName() + " " + request.lastName();

                CreateCustomerRequest customerRequest = new CreateCustomerRequest(
                                fullName,
                                request.documentId(),
                                request.email());

                CustomerResponse customerResponse = customerService.create(customerRequest);

                // 4. Link User to Customer
                Customer customer = customerRepository.findById(customerResponse.id())
                                .orElseThrow(() -> new ResourceNotFoundException("Customer not found after creation"));

                user.setCustomer(customer);

                User savedUser = userRepository.save(user);

                // JWT tokens are now generated by Keycloak, so we return empty or partial
                // response
                return userMapper.toResponse(savedUser, "keycloak-managed", "keycloak-managed");
        }

        @Override
        @Transactional
        public void deactivateUser(UUID userId) {
                User user = userRepository.findById(userId)
                                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
                user.setActive(false);
                userRepository.save(user);
        }

        @Override
        @Transactional
        public User syncWithKeycloak(String email, String fullName, com.banka.corebank.user.enums.UserRole role) {
                User user = userRepository.findByEmail(email)
                                .orElseGet(() -> {
                                        // 1. Trigger the existing registration chain
                                        CreateCustomerRequest customerRequest = new CreateCustomerRequest(
                                                        fullName != null ? fullName : "Nuevo Usuario",
                                                        "PENDIENTE-" + UUID.randomUUID().toString().substring(0, 8),
                                                        email);

                                        CustomerResponse customerResponse = customerService.create(customerRequest);

                                        Customer customer = customerRepository.findById(customerResponse.id())
                                                        .orElseThrow(() -> new ResourceNotFoundException(
                                                                        "Customer not found after JIT creation"));

                                        User newUser = new User();
                                        newUser.setEmail(email);
                                        newUser.setPassword("{noop}keycloak-managed");
                                        newUser.setRole(role != null ? role
                                                        : com.banka.corebank.user.enums.UserRole.USER);
                                        newUser.setCustomer(customer);

                                        return userRepository.save(newUser);
                                });

                // 2. Synchronize Role and Name if they have changed or are defaults
                boolean updated = false;
                if (role != null && user.getRole() != role) {
                        user.setRole(role);
                        updated = true;
                }

                if (fullName != null && user.getCustomer() != null &&
                                ("Nuevo Usuario".equals(user.getCustomer().getName()) || !fullName.equals(user.getCustomer().getName()))) {
                        user.getCustomer().setName(fullName);
                        customerRepository.save(user.getCustomer());
                        updated = true;
                }

                if (updated) {
                        return userRepository.save(user);
                }

                return user;
        }
}